### ISSUE TITLE
Segmentation fault at the end of program

### ISSUE THREAD

**Issue by kruesip** [ethz-asl/ethzasl_icp_mapping#11]
I get a seg fault at the end of every program where I use a variable of type `PointMatcher<float>::DataPoints`.

For example, I have the following test program (in a ROS package that has ethzasl_icp_mapper as a dependency):
```
#include "pointmatcher/PointMatcher.h"
using namespace PointMatcherSupport;
typedef PointMatcher<float> PM;
typedef PM::DataPoints DP;
int main(int argc, char **argv)
{  
  if(true) { DP test; }
  printf("finished\n");  
  return 0;
}
```
This creates the following output with gdb:
```
(gdb) run
Starting program: /home/kruesip/Repositories/asrl_navigation/asrl_graphnav/python_asrl_icp_navigation/bin/testExec 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
finished

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7a1427c in ~Registrar (this=0x7ffff7dd94b0, __in_chrg=<optimized out>)
    at /tmp/buildd/ros-groovy-ethzasl-icp-mapping-0.9.5/debian/ros-groovy-ethzasl-icp-mapping/opt/ros/groovy/stacks/ethzasl_icp_mapping/libpointmatcher/upstream_src/pointmatcher/Registrar.h:135
135     /tmp/buildd/ros-groovy-ethzasl-icp-mapping-0.9.5/debian/ros-groovy-ethzasl-icp-mapping/opt/ros/groovy/stacks/ethzasl_icp_mapping/libpointmatcher/upstream_src/pointmatcher/Registrar.h: No such file or directory.
(gdb) bt
#0  0x00007ffff7a1427c in ~Registrar (this=0x7ffff7dd94b0, __in_chrg=<optimized out>)
    at /tmp/buildd/ros-groovy-ethzasl-icp-mapping-0.9.5/debian/ros-groovy-ethzasl-icp-mapping/opt/ros/groovy/stacks/ethzasl_icp_mapping/libpointmatcher/upstream_src/pointmatcher/Registrar.h:135
#1  PointMatcher<double>::~PointMatcher (this=0x7ffff7dd9360, __in_chrg=<optimized out>)
    at /tmp/buildd/ros-groovy-ethzasl-icp-mapping-0.9.5/debian/ros-groovy-ethzasl-icp-mapping/opt/ros/groovy/stacks/ethzasl_icp_mapping/libpointmatcher/upstream_src/pointmatcher/PointMatcher.h:119
#2  0x00007ffff6e20d1d in __cxa_finalize () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007ffff576ae36 in __do_global_dtors_aux () from /opt/ros/groovy/stacks/ethzasl_icp_mapping/libpointmatcher_ros/lib/libpointmatcher_ros.so
#4  0x00007fffffffdb00 in ?? ()
#5  0x00007fffffffdd00 in ?? ()
#6  0x00007ffff585e081 in _fini () from /opt/ros/groovy/stacks/ethzasl_icp_mapping/libpointmatcher_ros/lib/libpointmatcher_ros.so
#7  0x00007fffffffdd00 in ?? ()
#8  0x00007ffff7de992d in ?? () from /lib64/ld-linux-x86-64.so.2
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

**Comment by pomerlef** [comment]
@kruesip is that still an issue?

**Comment by kruesip** [comment]
@pomerlef no, seems to be solved.
